task:
  skip: "changesIncludeOnly('.github/**' , 'doc/**', '**.md', 'Doxyfile')"

  matrix:
    - name: Alpine arm64
      arm_container:
        image: alpine:latest
      install_script: |
        apk update
        apk add build-base cmake curl g++ git

    - name: FreeBSD 14.2
      freebsd_instance:
        image_family: freebsd-14-2
      install_script: |
        pkg install -y cmake git

  build_script: |
    ./init.sh
    cmake -S . -B build -DCMAKE_CXX_STANDARD=17
    cmake --build build
  test_script: |
    ctest --output-on-failure --test-dir build
