codecov:
  require_ci_to_pass: false

ignore:
  - "deps"
  - "include/upa/idna.h"
  - "include/upa/url_for_*.h"
  - "src/idna.cpp"
  - "test"

coverage:
  status:
    project:
      default:
        threshold: 0.5%
