// Copyright 2019-2023 Rimas Misevičius
// Distributed under the BSD-style license that can be
// found in the LICENSE file.
//

#include "url_percent_encode.h"
#include <iomanip>
#include <iostream>

#ifndef WHATWG_CPP_17
#error "This file requires C++17 compiler"
#endif

using namespace upa;

template <typename CodePointSet>
void dumpSet(std::ostream& out, const char* type, const char* name, const CodePointSet& cpset) {
    out << std::setfill('0') << std::hex;

    out << "const " << type << " " << name << " = {\n    ";
    // find last non-zero value in array
    std::size_t size = cpset.arr_size();
    while (size > 0 && cpset.arr_val(size - 1) == 0)
        --size;
    // output array values
    for (std::size_t i = 0; i < size; ++i) {
        if (i > 0) out << ((i % 16) == 0 ? ",\n    " : ", ");
        out << "0x" << std::setw(2) << unsigned(cpset.arr_val(i));
    }
    out << "\n};\n";
}

#define DUMP_SET(type, name) dumpSet(out, #type, #name, name)

void dumpAll(std::ostream& out) {
    out << "// These data were generated by tools/dumpCharBitSets.cpp program.\n";

    DUMP_SET(code_point_set, fragment_no_encode_set);
    DUMP_SET(code_point_set, query_no_encode_set);
    DUMP_SET(code_point_set, special_query_no_encode_set);
    DUMP_SET(code_point_set, path_no_encode_set);
    DUMP_SET(code_point_set, raw_path_no_encode_set);
    DUMP_SET(code_point_set, posix_path_no_encode_set);
    DUMP_SET(code_point_set, userinfo_no_encode_set);
    DUMP_SET(code_point_set, component_no_encode_set);

    using namespace detail;
    out << "\n" "namespace detail {\n";
    DUMP_SET(code_points_multiset, code_points);
    out << "} // namespace detail\n";
}

int main() {
    dumpAll(std::cout);

    return 0;
}
