#include "url_percent_encode.h"
#include <iomanip>
#include <iostream>

#ifndef WHATWG__CPP_17
#error "This file requires C++17 compiler"
#endif

using namespace whatwg::detail;

void dumpSet(std::ostream& out) {
    out << std::setfill('0') << std::hex;
    out << "// This array was generated by tools/dumpCharBitSets.cpp program.\n";
    out << "const uint8_t kCharBitSets[0x" << kCharBitSets.size() << "] = {";
    for (size_t i = 0; i < kCharBitSets.size(); ++i) {
        if (i > 0) out << ",";
        out << ((i % 16 == 0) ? "\n    " : " ");
        out << "0x" << std::setw(2) << unsigned(kCharBitSets[i]);
    }
    out << "\n};\n";
}

int main() {
    dumpSet(std::cout);

    return 0;
}
